"""create taxonomy tables

Revision ID: 032f68276466
Revises: 
Create Date: 2026-03-08 08:09:10.256139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '032f68276466'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_tag_categories_is_active', 'tag_categories', ['is_active'], unique=False)
    op.create_index('ix_tag_categories_sort_order', 'tag_categories', ['sort_order'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tag_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_tags_category_id', 'tags', ['category_id'], unique=False)
    op.create_index('ix_tags_is_active', 'tags', ['is_active'], unique=False)
    op.create_index('ix_tags_priority', 'tags', ['priority'], unique=False)
    op.create_table('tag_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tag_rules_is_enabled', 'tag_rules', ['is_enabled'], unique=False)
    op.create_index('ix_tag_rules_priority', 'tag_rules', ['priority'], unique=False)
    op.create_index('ix_tag_rules_tag_id', 'tag_rules', ['tag_id'], unique=False)
    op.create_table('tag_rule_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['tag_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tag_rule_conditions_rule_id', 'tag_rule_conditions', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_rule_conditions_rule_id', table_name='tag_rule_conditions')
    op.drop_table('tag_rule_conditions')
    op.drop_index('ix_tag_rules_tag_id', table_name='tag_rules')
    op.drop_index('ix_tag_rules_priority', table_name='tag_rules')
    op.drop_index('ix_tag_rules_is_enabled', table_name='tag_rules')
    op.drop_table('tag_rules')
    op.drop_index('ix_tags_priority', table_name='tags')
    op.drop_index('ix_tags_is_active', table_name='tags')
    op.drop_index('ix_tags_category_id', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_tag_categories_sort_order', table_name='tag_categories')
    op.drop_index('ix_tag_categories_is_active', table_name='tag_categories')
    op.drop_table('tag_categories')
    # ### end Alembic commands ###